"""add is_admin to users and new_email to tokens

Revision ID: 2e50ec8bbe54
Revises: 61f372747915
Create Date: 2026-05-18 07:28:04.175206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e50ec8bbe54'
down_revision: Union[str, Sequence[str], None] = '61f372747915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('token_type', sa.String(length=100), nullable=False))
    op.add_column('email_verification_tokens', sa.Column('new_email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('email_verification_tokens', 'new_email')
    op.drop_column('email_verification_tokens', 'token_type')
    # ### end Alembic commands ###
