"""add server default and partial index to budget cycle

Revision ID: 61f372747915
Revises: 
Create Date: 2026-05-17 04:25:45.760700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f372747915'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_one_active_cycle_per_user', 'budget_cycles', ['user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_active_cycle_per_user', table_name='budget_cycles', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###
